import type { Company, Contact } from "./types";

const now = new Date().toISOString();
const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

function contact(
  id: string,
  name: string,
  role: string,
  type: Contact["type"],
  domain: Contact["domain"],
  strength: Contact["relationshipStrength"],
  lastDays: number,
): Contact {
  return {
    id,
    name,
    avatar: null,
    type,
    domain,
    company: null,
    role,
    relationshipStrength: strength,
    aiSummary: null,
    lastContactDate: daysAgo(lastDays),
    firstContactDate: daysAgo(lastDays + 180),
    contactFrequency: Math.max(1, Math.round(30 / Math.max(1, lastDays))),
    createdAt: now,
    updatedAt: now,
    platforms: [],
  };
}

export const MOCK_COMPANIES: Company[] = [
  // ─── PAYMENT ────────────────────────────────────────────────
  {
    id: "mock-stripe",
    name: "Stripe",
    domain: "stripe.com",
    sector: "payment",
    size: "enterprise",
    funding: "series-i",
    linkedin: "https://linkedin.com/company/stripe",
    website: "https://stripe.com",
    description: "Online payment processing for internet businesses.",
    createdAt: now,
    updatedAt: now,
    contactCount: 4,
    contacts: [
      contact("c-stripe-1", "Patrick Collison", "CEO", "partner", "payment", "warm", 12),
      contact("c-stripe-2", "John Collison", "President", "partner", "payment", "cold", 90),
      contact("c-stripe-3", "Will Gaybrick", "CFO", "partner", "finance", "cold", 60),
      contact("c-stripe-4", "Eileen O'Mara", "CRO", "lead", "payment", "warm", 8),
    ],
  },
  {
    id: "mock-adyen",
    name: "Adyen",
    domain: "adyen.com",
    sector: "payment",
    size: "enterprise",
    funding: "public",
    linkedin: "https://linkedin.com/company/adyen",
    website: "https://adyen.com",
    description: "Global payment platform for enterprise merchants.",
    createdAt: now,
    updatedAt: now,
    contactCount: 2,
    contacts: [
      contact("c-adyen-1", "Pieter van der Does", "CEO", "lead", "payment", "warm", 22),
      contact("c-adyen-2", "Ingo Uytdehaage", "Co-CEO", "lead", "payment", "cold", 80),
    ],
  },
  {
    id: "mock-qonto",
    name: "Qonto",
    domain: "qonto.com",
    sector: "payment",
    size: "scaleup",
    funding: "series-d",
    linkedin: "https://linkedin.com/company/qonto",
    website: "https://qonto.com",
    description: "Business banking for SMEs and freelancers in Europe.",
    createdAt: now,
    updatedAt: now,
    contactCount: 3,
    contacts: [
      contact("c-qonto-1", "Alexandre Prot", "CEO", "partner", "finance", "warm", 9),
      contact("c-qonto-2", "Steve Anavi", "Co-founder", "partner", "finance", "cold", 55),
      contact("c-qonto-3", "Marc-Antoine Lacroix", "Chief Product", "lead", "saas", "warm", 22),
    ],
  },
  {
    id: "mock-polar",
    name: "Polar",
    domain: "polar.sh",
    sector: "payment",
    size: "startup",
    funding: "seed",
    linkedin: "https://linkedin.com/company/polar-sh",
    website: "https://polar.sh",
    description: "Monetization for open source developers.",
    createdAt: now,
    updatedAt: now,
    contactCount: 1,
    contacts: [
      contact("c-polar-1", "Birk Jernström", "CEO", "lead", "payment", "warm", 6),
    ],
  },
  {
    id: "mock-lemonadepay",
    name: "Lemonade Pay",
    domain: "lemonadepay.io",
    sector: "payment",
    size: "startup",
    funding: "pre-seed",
    linkedin: null,
    website: "https://lemonadepay.io",
    description: "Embedded payments for creator platforms.",
    createdAt: now,
    updatedAt: now,
    contactCount: 0,
    contacts: [],
  },

  // ─── CRYPTO ─────────────────────────────────────────────────
  {
    id: "mock-coinbase",
    name: "Coinbase",
    domain: "coinbase.com",
    sector: "crypto",
    size: "enterprise",
    funding: "public",
    linkedin: "https://linkedin.com/company/coinbase",
    website: "https://coinbase.com",
    description: "Leading crypto exchange and on-ramp for the US market.",
    createdAt: now,
    updatedAt: now,
    contactCount: 3,
    contacts: [
      contact("c-cb-1", "Brian Armstrong", "CEO", "lead", "blockchain", "cold", 70),
      contact("c-cb-2", "Emilie Choi", "President & COO", "lead", "blockchain", "warm", 18),
      contact("c-cb-3", "Paul Grewal", "Chief Legal Officer", "advisor", "legal", "warm", 25),
    ],
  },
  {
    id: "mock-ledger",
    name: "Ledger",
    domain: "ledger.com",
    sector: "crypto",
    size: "scaleup",
    funding: "series-c",
    linkedin: "https://linkedin.com/company/ledgerhq",
    website: "https://ledger.com",
    description: "Hardware wallets and crypto security infrastructure.",
    createdAt: now,
    updatedAt: now,
    contactCount: 3,
    contacts: [
      contact("c-ledger-1", "Pascal Gauthier", "CEO", "partner", "blockchain", "hot", 4),
      contact("c-ledger-2", "Ian Rogers", "Chief Experience Officer", "partner", "blockchain", "warm", 14),
      contact("c-ledger-3", "Charles Guillemet", "CTO", "advisor", "blockchain", "warm", 21),
    ],
  },
  {
    id: "mock-circle",
    name: "Circle",
    domain: "circle.com",
    sector: "crypto",
    size: "enterprise",
    funding: "public",
    linkedin: "https://linkedin.com/company/centre-consortium",
    website: "https://circle.com",
    description: "Issuer of USDC stablecoin and crypto financial infrastructure.",
    createdAt: now,
    updatedAt: now,
    contactCount: 2,
    contacts: [
      contact("c-circle-1", "Jeremy Allaire", "CEO", "lead", "blockchain", "warm", 11),
      contact("c-circle-2", "Heath Tarbert", "Chief Legal Officer", "advisor", "legal", "cold", 50),
    ],
  },
  {
    id: "mock-kraken",
    name: "Kraken",
    domain: "kraken.com",
    sector: "crypto",
    size: "enterprise",
    funding: "private",
    linkedin: "https://linkedin.com/company/krakenfx",
    website: "https://kraken.com",
    description: "Crypto exchange known for security and institutional clients.",
    createdAt: now,
    updatedAt: now,
    contactCount: 2,
    contacts: [
      contact("c-kraken-1", "David Ripley", "CEO", "lead", "blockchain", "cold", 95),
      contact("c-kraken-2", "Arjun Sethi", "Co-CEO", "lead", "blockchain", "warm", 28),
    ],
  },
  {
    id: "mock-phantom",
    name: "Phantom",
    domain: "phantom.com",
    sector: "crypto",
    size: "scaleup",
    funding: "series-b",
    linkedin: "https://linkedin.com/company/phantomlabs",
    website: "https://phantom.com",
    description: "Self-custody crypto wallet for Solana, Ethereum and Bitcoin.",
    createdAt: now,
    updatedAt: now,
    contactCount: 2,
    contacts: [
      contact("c-phantom-1", "Brandon Millman", "CEO", "lead", "blockchain", "warm", 10),
      contact("c-phantom-2", "Francesco Agosti", "CTO", "advisor", "blockchain", "warm", 17),
    ],
  },
  {
    id: "mock-fireblocks",
    name: "Fireblocks",
    domain: "fireblocks.com",
    sector: "crypto",
    size: "scaleup",
    funding: "series-e",
    linkedin: "https://linkedin.com/company/fireblocks",
    website: "https://fireblocks.com",
    description: "Institutional digital asset custody and infrastructure.",
    createdAt: now,
    updatedAt: now,
    contactCount: 1,
    contacts: [
      contact("c-fb-1", "Michael Shaulov", "CEO", "lead", "blockchain", "warm", 19),
    ],
  },

  // ─── VC ─────────────────────────────────────────────────────
  {
    id: "mock-sequoia",
    name: "Sequoia Capital",
    domain: "sequoiacap.com",
    sector: "vc",
    size: "enterprise",
    funding: null,
    linkedin: "https://linkedin.com/company/sequoia-capital",
    website: "https://sequoiacap.com",
    description: "Partnering with founders from idea to IPO since 1972.",
    createdAt: now,
    updatedAt: now,
    contactCount: 3,
    contacts: [
      contact("c-seq-1", "Roelof Botha", "Senior Steward", "vc", "finance", "warm", 32),
      contact("c-seq-2", "Doug Leone", "Partner", "vc", "finance", "cold", 90),
      contact("c-seq-3", "Pat Grady", "Partner", "vc", "ai", "warm", 26),
    ],
  },
  {
    id: "mock-a16z",
    name: "Andreessen Horowitz",
    domain: "a16z.com",
    sector: "vc",
    size: "enterprise",
    funding: null,
    linkedin: "https://linkedin.com/company/andreessen-horowitz",
    website: "https://a16z.com",
    description: "Stage-agnostic VC investing in software, crypto and bio.",
    createdAt: now,
    updatedAt: now,
    contactCount: 3,
    contacts: [
      contact("c-a16z-1", "Marc Andreessen", "Co-founder", "vc", "saas", "cold", 110),
      contact("c-a16z-2", "Chris Dixon", "Head of Crypto", "vc", "blockchain", "warm", 15),
      contact("c-a16z-3", "Sriram Krishnan", "General Partner", "vc", "ai", "warm", 23),
    ],
  },
  {
    id: "mock-aglae",
    name: "Aglaé Ventures",
    domain: "aglaeventures.com",
    sector: "vc",
    size: "startup",
    funding: null,
    linkedin: "https://linkedin.com/company/aglae-ventures",
    website: "https://aglaeventures.com",
    description: "Early-stage venture fund backing European founders.",
    createdAt: now,
    updatedAt: now,
    contactCount: 2,
    contacts: [
      contact("c-aglae-1", "Bernard Arnault", "Founder", "vc", "finance", "cold", 200),
      contact("c-aglae-2", "Florian Ogier", "Partner", "vc", "finance", "warm", 28),
    ],
  },
  {
    id: "mock-paradigm",
    name: "Paradigm",
    domain: "paradigm.xyz",
    sector: "vc",
    size: "scaleup",
    funding: null,
    linkedin: "https://linkedin.com/company/paradigm-xyz",
    website: "https://paradigm.xyz",
    description: "Crypto-focused investment firm and research lab.",
    createdAt: now,
    updatedAt: now,
    contactCount: 2,
    contacts: [
      contact("c-para-1", "Matt Huang", "Co-founder", "vc", "blockchain", "warm", 13),
      contact("c-para-2", "Fred Ehrsam", "Co-founder", "vc", "blockchain", "cold", 75),
    ],
  },
  {
    id: "mock-index",
    name: "Index Ventures",
    domain: "indexventures.com",
    sector: "vc",
    size: "enterprise",
    funding: null,
    linkedin: "https://linkedin.com/company/index-ventures",
    website: "https://indexventures.com",
    description: "Multi-stage venture firm with offices in London and SF.",
    createdAt: now,
    updatedAt: now,
    contactCount: 2,
    contacts: [
      contact("c-idx-1", "Martin Mignot", "Partner", "vc", "saas", "warm", 20),
      contact("c-idx-2", "Jan Hammer", "Partner", "vc", "finance", "cold", 60),
    ],
  },

  // ─── PARTNER ────────────────────────────────────────────────
  {
    id: "mock-linear",
    name: "Linear",
    domain: "linear.app",
    sector: "partner",
    size: "scaleup",
    funding: "series-b",
    linkedin: "https://linkedin.com/company/linear",
    website: "https://linear.app",
    description: "Issue tracking and project management for software teams.",
    createdAt: now,
    updatedAt: now,
    contactCount: 3,
    contacts: [
      contact("c-linear-1", "Karri Saarinen", "CEO", "friend", "saas", "hot", 3),
      contact("c-linear-2", "Tuomas Artman", "CTO", "friend", "saas", "warm", 14),
      contact("c-linear-3", "Jori Lallo", "Co-founder", "friend", "saas", "warm", 21),
    ],
  },
  {
    id: "mock-vercel",
    name: "Vercel",
    domain: "vercel.com",
    sector: "partner",
    size: "scaleup",
    funding: "series-e",
    linkedin: "https://linkedin.com/company/vercel",
    website: "https://vercel.com",
    description: "Frontend cloud platform for Next.js and modern web apps.",
    createdAt: now,
    updatedAt: now,
    contactCount: 3,
    contacts: [
      contact("c-vercel-1", "Guillermo Rauch", "CEO", "partner", "saas", "hot", 2),
      contact("c-vercel-2", "Lee Robinson", "VP DX", "friend", "saas", "warm", 7),
      contact("c-vercel-3", "Tom Occhino", "VP Eng", "lead", "saas", "cold", 45),
    ],
  },
  {
    id: "mock-mistral",
    name: "Mistral AI",
    domain: "mistral.ai",
    sector: "partner",
    size: "scaleup",
    funding: "series-b",
    linkedin: "https://linkedin.com/company/mistralai",
    website: "https://mistral.ai",
    description: "Open-weight large language models from Paris.",
    createdAt: now,
    updatedAt: now,
    contactCount: 3,
    contacts: [
      contact("c-mistral-1", "Arthur Mensch", "CEO", "partner", "ai", "hot", 5),
      contact("c-mistral-2", "Guillaume Lample", "Chief Scientist", "advisor", "ai", "warm", 11),
      contact("c-mistral-3", "Timothée Lacroix", "CTO", "advisor", "ai", "warm", 16),
    ],
  },
  {
    id: "mock-hf",
    name: "Hugging Face",
    domain: "huggingface.co",
    sector: "partner",
    size: "scaleup",
    funding: "series-d",
    linkedin: "https://linkedin.com/company/huggingface",
    website: "https://huggingface.co",
    description: "The AI community building the future of ML.",
    createdAt: now,
    updatedAt: now,
    contactCount: 4,
    contacts: [
      contact("c-hf-1", "Clément Delangue", "CEO", "partner", "ai", "hot", 4),
      contact("c-hf-2", "Julien Chaumond", "CTO", "partner", "ai", "warm", 10),
      contact("c-hf-3", "Thomas Wolf", "Chief Science", "advisor", "ai", "warm", 25),
      contact("c-hf-4", "Omar Sanseviero", "Head DevRel", "friend", "ai", "warm", 17),
    ],
  },
  {
    id: "mock-notion",
    name: "Notion",
    domain: "notion.so",
    sector: "partner",
    size: "scaleup",
    funding: "series-c",
    linkedin: "https://linkedin.com/company/notionhq",
    website: "https://notion.so",
    description: "Connected workspace for notes, docs, and projects.",
    createdAt: now,
    updatedAt: now,
    contactCount: 2,
    contacts: [
      contact("c-notion-1", "Ivan Zhao", "CEO", "other", "saas", "cold", 75),
      contact("c-notion-2", "Akshay Kothari", "COO", "lead", "saas", "warm", 24),
    ],
  },
  {
    id: "mock-pennylane",
    name: "Pennylane",
    domain: "pennylane.com",
    sector: "partner",
    size: "scaleup",
    funding: "series-c",
    linkedin: "https://linkedin.com/company/pennylane-fr",
    website: "https://pennylane.com",
    description: "Accounting and financial management for French SMEs.",
    createdAt: now,
    updatedAt: now,
    contactCount: 2,
    contacts: [
      contact("c-penny-1", "Arthur Waller", "CEO", "lead", "finance", "warm", 13),
      contact("c-penny-2", "Edouard Mascré", "Co-founder", "lead", "finance", "cold", 80),
    ],
  },
];
