import type { Reminder } from "./types";

const now = Date.now();
const at = (days: number, hours = 9) =>
  new Date(now + days * 86400000 + hours * 3600000).toISOString();

export const MOCK_REMINDERS: Reminder[] = [
  {
    id: "rem-1",
    contactId: "c-stripe-1",
    content: "Follow up on partnership integration deck",
    dueDate: at(-5),
    status: "pending",
    createdAt: at(-12),
    contact: { id: "c-stripe-1", name: "Patrick Collison" },
  },
  {
    id: "rem-2",
    contactId: "c-ledger-1",
    content: "Send updated MOU for hardware wallet pilot",
    dueDate: at(-2),
    status: "pending",
    createdAt: at(-8),
    contact: { id: "c-ledger-1", name: "Pascal Gauthier" },
  },
  {
    id: "rem-3",
    contactId: "c-mistral-1",
    content: "Reply to Arthur · confirm API quota and pricing",
    dueDate: at(-1),
    status: "pending",
    createdAt: at(-5),
    contact: { id: "c-mistral-1", name: "Arthur Mensch" },
  },
  {
    id: "rem-4",
    contactId: "c-linear-1",
    content: "Schedule Q2 product sync with Karri",
    dueDate: at(0, 14),
    status: "pending",
    createdAt: at(-3),
    contact: { id: "c-linear-1", name: "Karri Saarinen" },
  },
  {
    id: "rem-5",
    contactId: "c-vercel-1",
    content: "Intro call with Guillermo about edge runtime",
    dueDate: at(0, 17),
    status: "pending",
    createdAt: at(-1),
    contact: { id: "c-vercel-1", name: "Guillermo Rauch" },
  },
  {
    id: "rem-6",
    contactId: "c-cb-2",
    content: "Send executive summary deck to Emilie",
    dueDate: at(1),
    status: "pending",
    createdAt: at(-1),
    contact: { id: "c-cb-2", name: "Emilie Choi" },
  },
  {
    id: "rem-7",
    contactId: "c-a16z-2",
    content: "Prep for Chris Dixon intro · crypto thesis brief",
    dueDate: at(2),
    status: "pending",
    createdAt: at(-2),
    contact: { id: "c-a16z-2", name: "Chris Dixon" },
  },
  {
    id: "rem-8",
    contactId: "c-qonto-1",
    content: "Quarterly partnership review with Alexandre",
    dueDate: at(3),
    status: "pending",
    createdAt: at(-4),
    contact: { id: "c-qonto-1", name: "Alexandre Prot" },
  },
  {
    id: "rem-9",
    contactId: "c-hf-1",
    content: "Discuss model hosting agreement with Clément",
    dueDate: at(5),
    status: "pending",
    createdAt: at(-7),
    contact: { id: "c-hf-1", name: "Clément Delangue" },
  },
  {
    id: "rem-10",
    contactId: "c-circle-1",
    content: "USDC settlement integration follow-up",
    dueDate: at(8),
    status: "pending",
    createdAt: at(-2),
    contact: { id: "c-circle-1", name: "Jeremy Allaire" },
  },
  {
    id: "rem-11",
    contactId: "c-seq-3",
    content: "Send investor update to Pat Grady",
    dueDate: at(14),
    status: "pending",
    createdAt: at(-6),
    contact: { id: "c-seq-3", name: "Pat Grady" },
  },
  {
    id: "rem-12",
    contactId: "c-phantom-1",
    content: "Discuss Solana wallet onboarding flow",
    dueDate: at(21),
    status: "pending",
    createdAt: at(-3),
    contact: { id: "c-phantom-1", name: "Brandon Millman" },
  },
  {
    id: "rem-13",
    contactId: "c-aglae-2",
    content: "Coffee with Florian · fund III status",
    dueDate: at(-10),
    status: "done",
    createdAt: at(-20),
    contact: { id: "c-aglae-2", name: "Florian Ogier" },
  },
  {
    id: "rem-14",
    contactId: "c-ramp-1",
    content: "Demo Suby card issuing to Eric",
    dueDate: at(-7),
    status: "done",
    createdAt: at(-15),
    contact: { id: "c-ramp-1", name: "Eric Glyman" },
  },
];
